name = "NumericalMethodsInQuantumMechanics"
uuid = "a831be1b-f0b9-43c6-81be-72750fc7bb58"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
Compat = "3.25"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
